baseURL: 'https://halon.cc/'
languageCode: it
DefaultContentLanguage: it
title: halon
theme: PaperMod

googleAnalytics: UA-188035113-1

copyright: Everything is mine


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

languages:
    it:
        languageName: "Italiano"
        weight: 1
        menu:
            main:
                - identifier: categories
                  name: categories
                  url: /categories/
                  weight: 10
                - identifier: archivio
                  name: archivio
                  url: /archive/
                  weight: 20

    en:
        languageName: ":en:"
        languageAltTitle: English
        weight: 2
        menu:
            main:
                - identifier: categories
                  name: categories
                  url: /categories/
                  weight: 10
                - identifier: archive
                  name: archive
                  url: /archive/
                  weight: 20
        title: halon En
        profileMode:
            enabled: true
            title: halon's blog
            imageUrl: "../profpic.jpg"
            # imageTitle: my image
            imageWidth: 120
            imageHeight: 120
            subtitle: "Welcome to everyone in my little world"
            buttons:
              - name: blog
                url: "posts"
              - name: "about me"
                url: "about-me"


outputs:
    home:
        - HTML
        - RSS
        - JSON

assets:
         favicon: "favicon.ico"


params:
  profileMode:
    enabled: true
    title: "halon's site" # optional default will be site title
    subtitle: "Bentenut* a tutt* nel mio piccolo mondo"
    imageUrl: "profpic.jpg"
    imageTitle: "<title of image as alt>"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: blog
        url: "posts"
      - name: chi sono
        url: "chi-sono"
      - name: Da 0 a Maratona
        url: "da-0-a-maratona"
      - name: Leggo cose
        url: "libreria"
  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/halon176/"
    - name: telegram
      url: "https://t.me/joinchat/t3HvXSV8Yn1jZTQ0"
    - name: twitter
      url: "https://twitter.com/halon_by"
    - name: youtube
      url: "https://www.youtube.com/channel/UCejuBRsBy7k_hKfkO8VTPfg"
    - name: email
      url: "mailto:hello@halon.cc"
    - name: github
      url: "https://github.com/halon176"
    - name: discord
      url: "https://discordapp.com/users/199192913064886272"
    - name: lastfm
      url: "https://www.last.fm/user/halon176"
    - name: spotify
      url: "https://open.spotify.com/user/11148187901"
    - name: steam
      url: "https://steamcommunity.com/id/hakon_by/"
    - name: rss
      url: index.xml
  domain: "halon.cc"
  remark42Url: "https://remark42.halon.cc"

  env: production
  ShowReadingTime: true
  comments: true
  ShowShareButtons: true
  author: halon
  ShowFullTextinRSS: true